Reduce package size
Publishing @fartlabs/sql-embedder@0.0.1 ...
error: Failed to publish @fartlabs/sql-embedder@0.0.1

Caused by:
    Failed to publish @fartlabs/sql-embedder at 0.0.1: package too large as limit has been exceeded by '/lib/sql.wasm', max size is 20971520, got 20977704
Command: /home/runner/.npm/_npx/91d31d47806d2506/node_modules/jsr/.download/v2.6.7/linux/deno publish
CWD: /home/runner/work/sql-embedder/sql-embedder
Output:
Child process exited with: 1